
name: aarch64 Windows Test

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-11-arm

    name: >-
      "arm test"

    steps:
      - uses: actions/checkout@v4

      - name: Run test
        run: |
          cd test
          .\einsteinbinary_windows_aarch64.exe -i p2030.1776842406.G53.17+02.80.N.b0s0g0.00000_2835.bin4 -t stochastic_full.bank -l p2030.1776842406.G53.17+02.80.N.b0s0g0.00000.zap -o results.cand0 -c p2030.1776842406.G53.17+02.80.N.b0s0g0.00000_2818.cpt -A 0.08 -P 3.0 -f 400.0 -W -z
          type stderr.txt